mysite/cards/urls.py
from django.urls import path, re_path, reverse_lazy
from . import views

app_name = 'cards'
urlpatterns = [
    path('', views.WordListView.as_view(), name='all'),
    path('word/<int:pk>', views.WordDetailView.as_view(), name='word_detail'),
    path('word/create', views.WordCreateView.as_view(success_url=reverse_lazy('cards:all')), name='word_create'),
    path('word/<int:pk>/update', views.WordUpdateView.as_view(success_url=reverse_lazy('cards:all')),
         name='word_update'),
    path('word/<int:pk>/delete', views.WordDeleteView.as_view(success_url=reverse_lazy('cards:all')),
         name='word_delete'),
    path('word/<int:pk>/meaning', views.MeaningCreateView.as_view(success_url=reverse_lazy(
        'cards:word_detail')), name='word_meaning_create'),
    path('word_meaning/<int:pk>', views.CrossDetailView.as_view(), name='word_meaning_detail'),
    path('word_meaning/<int:pk>/delete', views.CrossDeleteView.as_view(success_url=reverse_lazy('cards:word_detail')),
         name='word_meaning_delete'),
    path('word_meaning/<int:pk>/update', views.CrossUpdateView.as_view(success_url=reverse_lazy('cards:word_detail')),
         name='word_meaning_update'),
    path('word_meaning/<int:pk>/comment', views.CommentCreateView.as_view(success_url=reverse_lazy(
        'cards:word_meaning_detail')), name='word_meaning_comment_create'),
    path('meaning/<int:pk>/delete', views.MeaningDeleteView.as_view(success_url=reverse_lazy('cards:meaning_list')),
         name='meaning_delete'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(success_url=reverse_lazy('cards:word_meaning_detail')),
         name='word_meaning_comment_delete'),
    path('comment/<int:pk>/update',
         views.CommentUpdateView.as_view(success_url=reverse_lazy('cards:word_meaning_detail')),
         name='word_meaning_comment_update'),
    path('tag_group_words/', views.TagGroupsView.as_view(), name='tag_group_words_get'),
    path('tag_group_words/<str:tag_name>/<str:mix_up>/<int:first>/<int:last>/<str:field>/<str:show>/',
         views.TagGroupsView.as_view(), name='tag_group_words'),
    path('meaning_list', views.MeaningListView.as_view(), name='meaning_list'),
    path('meaning/<int:pk>', views.MeaningDetailView.as_view(), name='meaning_detail'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('cards/', include('cards.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

mysite/cards/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings
from taggit.managers import TaggableManager


class Word(models.Model):
    writing = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(1, "Word must be greater than 1 characters")]
    )
    old_writing = models.CharField(max_length=200)
    transcription = models.CharField(max_length=200)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    meanings = models.ManyToManyField('Meaning', through='CrossTable')
    tags = TaggableManager(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("writing", "owner")

    def __str__(self):
        return self.writing


class Meaning(models.Model):
    text = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(1, "Meaning must be greater than 1 characters")]
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("text", "owner")

    def __str__(self):
        return self.text


class CrossTable(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    meaning = models.ForeignKey(Meaning, on_delete=models.CASCADE)
    username = models.CharField(max_length=200, default=None)

    class Meta:
        unique_together = ("word", "meaning", "username")


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    word_meaning = models.ForeignKey(CrossTable, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("text", "word_meaning", "owner")

    def __str__(self):
        if len(self.text) < 15:
            return self.text
        return self.text[:11] + ' ...'


class Tag(models.Model):
    text = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(1, "Tag must be greater than 1 characters")]
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("text", "owner")

    def __str__(self):
        return self.text

mysite/cards/forms.py
from django import forms
from cards.models import Word, Meaning, Comment


class CreateForm(forms.ModelForm):
    class Meta:
        model = Word
        fields = ['writing', 'old_writing', 'transcription', 'tags']


class MeaningForm(forms.Form):
    meaning = forms.CharField(required=True, max_length=500, min_length=1, strip=True)


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)


class CommentUpdateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class CrossMeaningUpdateForm(forms.ModelForm):
    class Meta:
        model = Meaning
        fields = ['text']


class TagAddForm(forms.Form):
    new_tag = forms.CharField(required=True, max_length=500, min_length=1, strip=True)

mysite/cards/views.py
import json
from copy import deepcopy

from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView

from cards.forms import CreateForm, MeaningForm, CommentForm, CrossMeaningUpdateForm, CommentUpdateForm, TagAddForm
from cards.models import Word, Meaning, CrossTable, Comment, Tag
from cards.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerWordDeleteView, \
    OwnerMeaningDeleteView, OwnerCrossDeleteView, OwnerCommentDeleteView, OwnerCrossUpdateView, \
    OwnerCommentUpdateView
from django.urls import reverse
from django.contrib.humanize.templatetags.humanize import naturaltime

from cards.utils import dump_queries

from django.db.models import Q

from random import shuffle


class WordListView(OwnerListView):
    model = Word
    template_name = "cards/word_list.html"

    def get(self, request):
        word_list = None
        searching = None
        word_groups = None
        if request.user.is_authenticated:
            searching = request.GET.get("search", False)
            if searching:
                query = Q(writing__icontains=searching)
                query.add(Q(old_writing__icontains=searching), Q.OR)
                query.add(Q(transcription__icontains=searching), Q.OR)
                query.add(Q(tags__name__in=[searching]), Q.OR)
                word_list = Word.objects.filter(query, owner=self.request.user).select_related().distinct().order_by(
                    '-updated_at')[:10000]
            else:
                word_list = Word.objects.filter(owner=self.request.user).order_by('-updated_at')[:10000]

            for obj in word_list:
                obj.natural_updated = naturaltime(obj.updated_at)

            word_groups = Tag.objects.filter(owner=self.request.user)

        ctx = {'word_list': word_list, 'search': searching, 'word_groups': word_groups}
        return render(request, self.template_name, ctx)


class WordDetailView(OwnerDetailView):
    model = Word
    template_name = "cards/word_detail.html"

    def get(self, request, pk):
        word = Word.objects.get(id=pk)
        cross_objs = list(CrossTable.objects.filter(word=word).order_by('-meaning__updated_at'))
        l_all = list()
        for cross_obj in cross_objs:
            l_comms = list()
            for el in list(cross_obj.comment_set.all()):
                if len(el.text) < 21:
                    l_comms.append(el.text)
                else:
                    l_comms.append((el.text[:17] + '...'))
            l_comms = ', '.join(l_comms)
            l_all.append((cross_obj, l_comms))
        meaning_form = MeaningForm()
        context = {
            'word': word,
            'cross_objs_all': l_all,
            'cross_objs': cross_objs,
            'meaning_form': meaning_form}
        return render(request, self.template_name, context)


class WordCreateView(LoginRequiredMixin, View):
    template_name = 'cards/word_form.html'
    success_url = reverse_lazy('cards:all')

    def get(self, request, pk=None):
        form = CreateForm(initial={'tags': '0, '})
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST)

        if not '0' in request.POST['tags']:
            err = "Enter '0' into tags-field"
            ctx = {'form': form, 'err': err}
            return render(request, self.template_name, ctx)

        if not form.is_valid():
            err = "Fill correctly all the fields"
            ctx = {'form': form, 'err': err}
            return render(request, self.template_name, ctx)

        if not Word.objects.filter(writing=request.POST['writing'], old_writing=request.POST['old_writing'],
                                   transcription=request.POST['transcription'], owner=request.user):
            word = form.save(commit=False)
            word.owner = self.request.user
            word.save()
            form.save_m2m()

            for tag in word.tags.all():
                Tag.objects.get_or_create(text=tag, owner=self.request.user)

        return redirect(self.success_url)


class WordUpdateView(LoginRequiredMixin, View):
    template_name = 'cards/word_form.html'
    success_url = reverse_lazy('cards:all')

    def get(self, request, pk):
        word = get_object_or_404(Word, id=pk, owner=self.request.user)
        form = CreateForm(instance=word)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        word = get_object_or_404(Word, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, instance=word)

        if not '0' in request.POST['tags']:
            err = "Enter '0' into tags-field"
            ctx = {'form': form, 'err': err}
            return render(request, self.template_name, ctx)

        if not form.is_valid():
            err = "Fill correctly all the fields"
            ctx = {'form': form, 'err': err}
            return render(request, self.template_name, ctx)

        word = form.save(commit=False)
        word.save()
        form.save_m2m()

        for tag in word.tags.all():
            Tag.objects.get_or_create(text=tag, owner=self.request.user)

        return redirect(self.success_url)


class WordDeleteView(OwnerWordDeleteView):
    model = Word


class MeaningDeleteView(OwnerMeaningDeleteView):
    model = Meaning


class MeaningCreateView(LoginRequiredMixin, View):
    success_url = reverse_lazy('cards:word_detail')

    def post(self, request, pk):
        word = get_object_or_404(Word, id=pk)
        meaning, created = Meaning.objects.get_or_create(text=request.POST['meaning'], owner=self.request.user)
        CrossTable.objects.get_or_create(word=word, meaning=meaning, username=request.user.username)
        return redirect(reverse('cards:word_detail', args=[pk]))


class CrossUpdateView(OwnerCrossUpdateView):
    template_name = 'cards/crosstable_form.html'

    def get(self, request, pk):
        crosstable = get_object_or_404(CrossTable, id=pk, username=self.request.user.username)
        form = CrossMeaningUpdateForm(instance=crosstable.meaning)
        ctx = {'form': form, 'crosstable': crosstable}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        crosstable = get_object_or_404(CrossTable, id=pk, username=self.request.user.username)
        form = CrossMeaningUpdateForm(request.POST, instance=crosstable.meaning)

        if not form.is_valid():
            ctx = {'form': form, 'crosstable': crosstable}
            return render(request, self.template_name, ctx)

        cross_meaning_text = form.save(commit=False)
        try:
            cross_meaning_text.save()
            form.save_m2m()
        except:
            word = crosstable.word
            meaning = Meaning.objects.get(text=cross_meaning_text, owner=self.request.user)
            CrossTable.objects.filter(id=pk, username=self.request.user.username).delete()
            CrossTable.objects.get_or_create(word=word, meaning=meaning, username=request.user.username)
        return redirect(reverse('cards:word_detail', args=[crosstable.word.id]))


class CrossDeleteView(OwnerCrossDeleteView):
    model = CrossTable
    template_name = "cards/word_meaning_delete.html"

    def get_success_url(self):
        word = self.object.word
        return reverse('cards:word_detail', args=[word.id])


class CommentCreateView(LoginRequiredMixin, View):
    success_url = reverse_lazy('cards:word_meaning_detail')

    def post(self, request, pk):
        word_meaning = get_object_or_404(CrossTable, id=pk)
        comment = Comment(text=request.POST['comment'], owner=self.request.user, word_meaning=word_meaning)
        comment.save()
        return redirect(reverse('cards:word_meaning_detail', args=[pk]))


class CommentUpdateView(OwnerCommentUpdateView):
    template_name = 'cards/comment_form.html'

    def get(self, request, pk):
        comment = get_object_or_404(Comment, id=pk, owner=self.request.user)
        form = CommentUpdateForm(instance=comment)
        ctx = {'form': form, 'comment': comment}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        comment = get_object_or_404(Comment, id=pk, owner=self.request.user)
        form = CommentUpdateForm(request.POST, instance=comment)

        if not form.is_valid():
            ctx = {'form': form, 'comment': comment}
            return render(request, self.template_name, ctx)

        comment_text = form.save(commit=False)
        comment_text.save()
        form.save_m2m()

        return redirect(reverse('cards:word_meaning_detail', args=[comment.word_meaning.id]))


class CommentDeleteView(OwnerCommentDeleteView):
    model = Comment
    template_name = "cards/comment_delete.html"

    def get_success_url(self):
        word_meaning = self.object.word_meaning
        return reverse('cards:word_meaning_detail', args=[word_meaning.id])


class CrossDetailView(OwnerDetailView):
    model = CrossTable
    template_name = "cards/word_meaning_detail.html"

    def get(self, request, pk):
        crosstable = CrossTable.objects.get(id=pk)
        comments = Comment.objects.filter(word_meaning=crosstable)
        comment_form = CommentForm()
        context = {'crosstable': crosstable, 'comments': comments, 'comment_form': comment_form}
        return render(request, self.template_name, context)


class TagGroupsView(View):
    template_name = "cards/tag_words.html"

    def get(self, request, tag_name=None, mix_up='no', first=None, last=None, field=None, show=None):
        if not tag_name:
            tag_name = request.GET.get('tag_name', '')

mysite/cards/templates/cards/comment_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <h1>Delete Comment</h1>

    <p>Are you sure you want to delete</p>
    <p>{{ comment.text }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Yes, delete.">
        <a href="{% url 'cards:word_meaning_detail' comment.word_meaning.id %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

mysite/cards/templates/cards/comment_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <p>
    <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel"
               onclick="window.location.href='{% url 'cards:word_meaning_detail' comment.word_meaning.id %}';
                       return false;">
    </form>
    </p>
{% endblock %}

mysite/cards/templates/cards/crosstable_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <p>
    <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel"
               onclick="window.location.href='{% url 'cards:word_detail' crosstable.word.id %}'
                       ;return false;">
    </form>
    </p>
{% endblock %}

mysite/cards/templates/cards/meaning_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <h1>Delete Meaning</h1>

    <p>Are you sure you want to delete the item: {{ meaning }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock %}

mysite/cards/templates/cards/meaning_detail.html
{% extends "base_menu.html" %}
{% load crispy_forms_filters %}
{% load humanize %}
{% block head %}
    <style>
        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 10;
            display: none;
            background-color: rgba(0, 0, 0, 0.5); /*dim the background*/
        }
    </style>
{% endblock %}
{% block content %}
    <span style="float: right;">
</span>
    <br>
    <h1>{{ meaning.text }}</h1>
    <p>
        ({{ meaning.updated_at|naturaltime }})
    </p>
    <br> <br>
    {% for word in words %}
        <p><h2><a href="{% url 'cards:word_detail' word.id %}">{{ word.writing }}</a></h2>
        ({{ word.updated_at|naturaltime }})
        </p>
    {% endfor %}
{% endblock %}

mysite/cards/templates/cards/meaning_list.html
{% extends "base_menu.html" %}
{% load crispy_forms_filters %}
{% load humanize %}
{% block content %}
    <h1>Meanings</h1>
    <div style="float:right">
        {% if user.is_authenticated %}
            <form>
                <input type="text" placeholder="Search..." name="search"
                        {% if search %} value="{{ search }}" {% endif %}
                >
                <button type="submit"><i class="fa fa-search"></i></button>
                <a href="{% url 'cards:meaning_list' %}"><i class="fa fa-undo"></i></a>
            </form>
            <br><br>
            </div>
            <p>
                {% if meaning_list %}
                    <ul>
                        {% for meaning in meaning_list %}
                            <li>
                                <a href="{% url 'cards:meaning_detail' meaning.id %}">{{ meaning.text }}</a>
                                {% if meaning.owner == user and not meaning.word_set.all %}
                                    <a href="{% url 'cards:meaning_delete' meaning.id %}"><i
                                            class="fa fa-trash"></i></a>
                                {% endif %}
                                <br>
                                <small>
                                    posted
                                    {{ meaning.created_at|naturaltime }}
                                    <br>
                                    updated
                                    {{ meaning.updated_at|naturaltime }}
                                </small>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>There are no meanings in the database.</p>
                {% endif %}
            </p>
            <p>
                | <a href="{% url 'logout' %}?next={% url 'cards:meaning_list' %}">Logout</a> |
                {% else %}
            <div style="position: fixed; left: 395px;">
                <p>You are not authorized to see meaning list.</p>
                | <a href="{% url 'login' %}?next={% url 'cards:meaning_list' %}">Login</a> |
            </div>
        {% endif %}
            </p>
{% endblock %}

mysite/cards/templates/cards/word_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <h1>Delete Word</h1>

    <p>Are you sure you want to delete the item: {{ word }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock %}

mysite/cards/templates/cards/word_detail.html
{% extends "base_menu.html" %}
{% load crispy_forms_filters %}
{% load humanize %}
{% block head %}
    <style>
        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 10;
            display: none;
            background-color: rgba(0, 0, 0, 0.5); /*dim the background*/
        }
    </style>
{% endblock %}
{% block content %}
    <span style="float: right;">
({{ word.updated_at|naturaltime }})
        {% if word.owner == user %}
            <a href="{% url 'cards:word_update' word.id %}"><i class="fa fa-pencil"></i></a>
            <a href="{% url 'cards:word_delete' word.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
</span>
    <br>
    <h1>{{ word.writing }}</h1>
    <p>
    <h1>{{ word.old_writing }}</h1>
    </p>
    <br>
    <p>
        {{ word.transcription }}
    </p>
    <br><br><br>
    {% if word.tags.all %}
        <p>
            <i>Tags:
                {% for tag in word.tags.all %}
                    <span style="border:1px grey solid; background-color: LightGreen;">
      <a href="{% url 'cards:tag_group_words' tag.name 'no' 1 10000 'writing' 10000 %}">{{ tag.name }}</a></span>
                {% endfor %}
            </i>
        </p>
    {% endif %}
    <br>
    <p>
    </p>
    {% if user.is_authenticated %}
        <br clear="all"/>
        <p>
            {% load crispy_forms_tags %}
        <form method="post" action="{% url 'cards:word_meaning_create' word.id %}">
            {% csrf_token %}
            {{ meaning_form|crispy }}
            <input type="submit" value="Submit">
            <input type="submit" value="All Words" onclick="window.location.href='{% url 'cards:all' %}';return false;">
        </form>
        </p>
    {% endif %}
    {% for cross_obj, comments in cross_objs_all %}
        {% if comments %}
            <p> <a href="{% url 'cards:word_meaning_detail' cross_obj.id %}">{{ cross_obj.meaning.text }}</a>
            &ensp;
            ({{ comments }})
            &emsp;&emsp;&emsp;
            ({{ cross_obj.meaning.updated_at|naturaltime }})
        {% else %}
            <a href="{% url 'cards:word_meaning_detail' cross_obj.id %}">{{ cross_obj.meaning.text }}</a>
            &emsp;&emsp;&emsp;
            ({{ cross_obj.meaning.updated_at|naturaltime }})
        {% endif %}
    {% if user == cross_obj.meaning.owner %}
        <a href="{% url 'cards:word_meaning_update' cross_obj.id %}"><i class="fa fa-pencil"></i></a>
        <a href="{% url 'cards:word_meaning_delete' cross_obj.id %}"><i class="fa fa-trash"></i></a>
    {% endif %}
    </p>
    {% endfor %}
{% endblock %}

mysite/cards/templates/cards/word_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if err %}
        <span style="color: #ff6600;"><b>{{ err }}</b></span></p>
    {% endif %}
    <p>
    <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'cards:all' %}';return false;">
    </form>
    </p>
{% endblock %}

mysite/cards/templates/cards/word_list.html
{% extends "base_menu.html" %}
{% load crispy_forms_filters %}
{% load humanize %}
{% block content %}
    <h1>Words</h1>
    <div style="float:right">
        <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
        {% if user.is_authenticated %}
            <form>
                <input type="text" placeholder="Search..." name="search"
                        {% if search %} value="{{ search }}" {% endif %}
                >
                <button type="submit"><i class="fa fa-search"></i></button>
                <a href="{% url 'cards:all' %}"><i class="fa fa-undo"></i></a>
            </form>
            <br><br>
            Group name &emsp;&emsp; Range &emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp; Mix up?
            <form action="tag_group_words">
                {% if word_groups %}
                    <select name="tag_name">
                        {% for group in word_groups %}
                            <option value="{{ group.text }}">{{ group.text }}</option>
                        {% endfor %}
                    </select>
                    <input type="text" , value="1" , name="first" , size="2">
                    -
                    <input type="text" , value="10000" , name="last" , size="2">
                    <select name="mix_up">
                        <option value="no">No</option>
                        <option value="yes">Yes</option>
                    </select>
                    <input type="text" , value="30" , name="show" , size="2">
                    <button type="submit"><i class="fa fa-check"></i></button>
                {% else %}
                    <select name="None">
                        <option value="None">There are no groups</option>
                    </select>
                {% endif %}
            </form>
            </div>
            <p>
                {% if word_list %}
                    <ul>
                        {% for word in word_list %}
                            <li>
                                <a href="{% url 'cards:word_detail' word.id %}">{{ word.writing }}</a>
                                <br>
                                <small>
                                    posted
                                    {{ word.created_at|naturaltime }}
                                    <br>
                                    updated
                                    {{ word.updated_at|naturaltime }}
                                </small>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>There are no words in the database.</p>
                {% endif %}
            </p>
            <p>
                <a href="{% url 'cards:word_create' %}">Add a Word</a> |
                <a href="{% url 'logout' %}?next={% url 'cards:all' %}">Logout</a>
                {% else %}
            <div style="position: fixed; left: 395px;">
                <p>You are not authorized to see word lists.</p>
                | <a href="{% url 'login' %}?next={% url 'cards:all' %}">Login</a> |
            </div>
        {% endif %}
    </p>
{% endblock %}

mysite/cards/templates/cards/word_meaning_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <h1>Delete Meaning</h1>

    <p>Are you sure you want to delete</p>
    <p>{{ crosstable.meaning.text }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Yes, delete.">
        <a href="{% url 'cards:word_detail' crosstable.word.id %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

mysite/cards/templates/cards/word_meaning_detail.html
{% extends "base_menu.html" %}
{% load crispy_forms_filters %}
{% load humanize %}
{% block head %}
    <style>
        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 10;
            display: none;
            background-color: rgba(0, 0, 0, 0.5); /*dim the background*/
        }
    </style>
{% endblock %}
{% block content %}
    <span style="float: right;">
{% if crosstable.username == user.username %}
    <a href="{% url 'cards:word_meaning_update' crosstable.id %}"><i class="fa fa-pencil"></i></a>
    <a href="{% url 'cards:word_meaning_delete' crosstable.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
    <h1><a href="{% url 'cards:meaning_detail' crosstable.meaning.id %}"
           target="_blank">{{ crosstable.meaning.text }}</a></h1>
    {% if user.is_authenticated %}
        <br clear="all"/>
        <p>
            {% load crispy_forms_tags %}
        <form method="post" action="{% url 'cards:word_meaning_comment_create' crosstable.id %}">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <input type="submit" value="Submit">
            <input type="submit" value="Word"
                   onclick="window.location.href='{% url 'cards:word_detail' crosstable.word.id %}';return false;">
        </form>
        </p>
    {% endif %}
    {% for comment in comments %}
        {{ comment.text }}
        {% if user == comment.owner %}
            &emsp;&emsp;&emsp;
            <a href="{% url 'cards:word_meaning_comment_update' comment.id %}"><i class="fa fa-pencil"></i></a>
            <a href="{% url 'cards:word_meaning_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
        </p>
    {% endfor %}
{% endblock %}